### ISSUE TITLE
RM manager portal (login session) becomes unresponsive when nodes are behind firewalls

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/scheduling-portal#459]
This occurs when node monitoring is requested or node is removed.

The following stack appears on server side thread dump:
```
"RMProxyUserInterface on pamr://0/Node2094227147" #432 prio=5 os_prio=0 tid=0x00007f643030c000 nid=0x2a31 runnable [0x00007f63ef7d9000]
   java.lang.Thread.State: RUNNABLE
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	- locked <0x000000009afd9540> (a java.net.SocksSocketImpl)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
	at com.sun.jndi.rmi.registry.RegistryContext.lookup(RegistryContext.java:132)
	at com.sun.jndi.toolkit.url.GenericURLContext.lookup(GenericURLContext.java:205)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at javax.management.remote.rmi.RMIConnector.findRMIServerJNDI(RMIConnector.java:1955)
	at javax.management.remote.rmi.RMIConnector.findRMIServer(RMIConnector.java:1922)
	at javax.management.remote.rmi.RMIConnector.connect(RMIConnector.java:287)
	- locked <0x000000009afd83a8> (a javax.management.remote.rmi.RMIConnector)
	at javax.management.remote.JMXConnectorFactory.connect(JMXConnectorFactory.java:270)
	at org.ow2.proactive.resourcemanager.common.util.RMListenerProxy.initNodeConnector(RMListenerProxy.java:377)
	at org.ow2.proactive.resourcemanager.common.util.RMListenerProxy.getNodeMBeanInfo(RMListenerProxy.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
	at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
	at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
	at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
	at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
	at org.objectweb.proactive.Service.serve(Service.java:119)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:203)
	at org.objectweb.proactive.Service.blockingServeOldest(Service.java:178)
	at org.objectweb.proactive.Service.fifoServing(Service.java:141)
	at org.objectweb.proactive.core.body.ActiveBody$FIFORunActive.runActivity(ActiveBody.java:329)
	at org.objectweb.proactive.core.body.ActiveBody.run(ActiveBody.java:167)
	at java.lang.Thread.run(Thread.java:748)
```

The server-side user session is blocked on a network RMI call timeout.

After the timeout is expired the session comes back to life.

**Comment by sophiesongge** [comment]
This one should be closed? @fviale

**Comment by fviale** [comment]
Fixed by modification at the scheduler-portal level (use proactive as protocol for monitoring instead of rmi).
